CREATE USER 'SKELETON'@'localhost' IDENTIFIED BY 'xxxx';
GRANT USAGE ON *.* TO 'SKELETON'@'localhost' IDENTIFIED BY 'xxxx';
CREATE DATABASE IF NOT EXISTS `SKELETON`;
GRANT ALL PRIVILEGES ON `SKELETON`.* TO 'SKELETON'@'localhost';
FLUSH PRIVILEGES;