# Move this to the apache conf folder and include.
# Enable the Macro module in the global httpd.conf:
# LoadModule macro_module modules/mod_macro.so
<Macro TIVSiteWWW $domain>
<IfModule ssl_module>
<VirtualHost *:80>
	ServerName www.$domain
	ServerAlias www.$domain $domain
	Redirect Permanent / https://www.$domain/
</VirtualHost>
<VirtualHost *:443>
	ServerName www.$domain:443
	ServerAlias www.$domain $domain

	<If "%{HTTP_HOST} != 'www.$domain'">
		Redirect "/" "https://www.$domain/"
	</If>

	DocumentRoot /var/www/u/www.$domain/public

	ErrorLog ${APACHE_LOG_DIR}/www.$domain-error.log
	CustomLog ${APACHE_LOG_DIR}/www.$domain-access.log combined

	SSLEngine on
	SSLOptions +StrictRequire

	# Prevent Beast attack
	SSLHonorCipherOrder on

	# SSL Compression (CRIME attack)
	SSLCompression off

	SSLProtocol             all -SSLv2 -SSLv3 -TLSv1
	SSLCipherSuite          ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK

	# Replace self-signed certificate with a real one!
	SSLCertificateFile		"/var/www/u/www.$domain/ssl/server.crt"
	SSLCertificateKeyFile	"/var/www/u/www.$domain/ssl/server.key"

</VirtualHost>
</IfModule>
</Macro>

